const D=window.DATA_SNAPSHOT;let active='POW';let charts=[];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=0)=>n==null?'—':Number(n).toLocaleString('vi-VN',{maximumFractionDigits:d});
function total(series,i){return Object.values(series).reduce((s,a)=>s+(Number(a[i])||0),0)}
function pct(a,b){return b?((a/b-1)*100):null}
function yoyClass(v){return v==null?'':v>=0?'up':'down'}
function destroy(){charts.forEach(c=>c.destroy());charts=[]}
function addChart(id,type,labels,datasets,opts={}){const el=document.getElementById(id);if(!el)return;charts.push(new Chart(el,{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${fmt(c.raw,1)}${opts.unit?' '+opts.unit:''}`}}},scales:{x:{stacked:!!opts.stacked,grid:{display:false}},y:{stacked:!!opts.stacked,beginAtZero:!!opts.zero}}}}))}
function cards(items){$('#kpis').innerHTML=items.map(x=>`<div class="stat-card"><span>${x.label}</span><strong>${x.value}</strong>${x.note?`<small class="${x.cls||''}">${x.note}</small>`:''}</div>`).join('')}
function panel(title,sub,id){return `<div class="chart-card"><div class="chart-title"><div><h3>${title}</h3><span>${sub}</span></div></div><div class="chart-box"><canvas id="${id}"></canvas></div></div>`}
function renderPOW(){const x=D.POW,n=x.months.length-1,prev=n-12;const gen=total(x.generation.series,n),rev=total(x.revenue.series,n),qc=total(x.qc.series,n),genYoY=pct(gen,total(x.generation.series,prev)),revYoY=pct(rev,total(x.revenue.series,prev));cards([{label:'Sản lượng T7/2026',value:fmt(gen,1)+' GWh',note:`${genYoY>=0?'+':''}${fmt(genYoY,1)}% YoY`,cls:yoyClass(genYoY)},{label:'Qc T7/2026',value:fmt(qc,1)+' GWh'},{label:'Doanh thu T7/2026',value:fmt(rev,1)+' tỷ',note:`${revYoY>=0?'+':''}${fmt(revYoY,1)}% YoY`,cls:yoyClass(revYoY)},{label:'Kỳ mới nhất',value:x.latest}]);
$('#charts').innerHTML=panel('Sản lượng điện theo nhà máy','Cột chồng · GWh','pow-gen')+panel('Sản lượng Qc theo nhà máy','Cột chồng · GWh','pow-qc')+panel('Doanh thu theo nhà máy','Cột chồng · tỷ đồng','pow-rev')+panel('Tổng sản lượng và Qc','So sánh tổng hệ thống','pow-total');
const ds=o=>Object.entries(o).map(([k,v])=>({label:k,data:v,borderWidth:1}));addChart('pow-gen','bar',x.months,ds(x.generation.series),{stacked:true,unit:'GWh',zero:true});addChart('pow-qc','bar',x.months,ds(x.qc.series),{stacked:true,unit:'GWh',zero:true});addChart('pow-rev','bar',x.months,ds(x.revenue.series),{stacked:true,unit:'tỷ đồng',zero:true});addChart('pow-total','line',x.months,[{label:'Sản lượng',data:x.months.map((_,i)=>total(x.generation.series,i)),tension:.25},{label:'Qc',data:x.months.map((_,i)=>total(x.qc.series,i)),tension:.25}],{unit:'GWh'});}
function renderFPT(){const x=D.FPT,n=x.years.length-1;const revYoY=pct(x.revenue[n],x.revenue[n-1]),pbtYoY=pct(x.pbt[n],x.pbt[n-1]);cards([{label:'Doanh thu 2025',value:fmt(x.revenue[n])+' tỷ',note:`+${fmt(revYoY,1)}% YoY`,cls:'up'},{label:'LNTT 2025',value:fmt(x.pbt[n])+' tỷ',note:`+${fmt(pbtYoY,1)}% YoY`,cls:'up'},{label:'Doanh thu 2026 YTD',value:fmt(x.ytd2026.revenue)+' tỷ'},{label:'CNTT nước ngoài 2026 YTD',value:fmt(x.ytd2026.overseas)+' tỷ'}]);
$('#charts').innerHTML=panel('Doanh thu và LNTT','2018–2025 · tỷ đồng','fpt-core')+panel('Cơ cấu doanh thu','Các mảng chính · tỷ đồng','fpt-mix')+panel('Biên LNTT','LNTT / doanh thu','fpt-margin')+panel('Động lực 2026 YTD','Tổng hợp từ sheet hiện tại','fpt-ytd');
addChart('fpt-core','line',x.years,[{label:'Doanh thu',data:x.revenue,tension:.25},{label:'LNTT',data:x.pbt,tension:.25}],{unit:'tỷ đồng'});addChart('fpt-mix','bar',x.years,Object.entries(x.segments).map(([k,v])=>({label:k,data:v})),{stacked:false,unit:'tỷ đồng',zero:true});addChart('fpt-margin','line',x.years,[{label:'Biên LNTT',data:x.pbt.map((v,i)=>v/x.revenue[i]*100),tension:.25}],{unit:'%'});addChart('fpt-ytd','bar',['Doanh thu','Công nghệ','CNTT nước ngoài','LNTT'],[{label:'2026 YTD',data:[x.ytd2026.revenue,x.ytd2026.technology,x.ytd2026.overseas,x.ytd2026.pbt]}],{unit:'tỷ đồng',zero:true});}
function renderREE(){const x=D.REE,n=x.quarters.length-1,revYoY=pct(x.quarterlyRevenue[n],x.quarterlyRevenue[n-4]),npYoY=pct(x.quarterlyNpatmi[n],x.quarterlyNpatmi[n-4]);cards([{label:'Doanh thu Q2/2026',value:fmt(x.quarterlyRevenue[n])+' tỷ',note:`${revYoY>=0?'+':''}${fmt(revYoY,1)}% YoY`,cls:yoyClass(revYoY)},{label:'LNST CĐ mẹ Q2/2026',value:fmt(x.quarterlyNpatmi[n])+' tỷ',note:`${npYoY>=0?'+':''}${fmt(npYoY,1)}% YoY`,cls:yoyClass(npYoY)},{label:'Doanh thu 2025',value:fmt(x.revenue.at(-1))+' tỷ'},{label:'LNST CĐ mẹ 2025',value:fmt(x.npatmi.at(-1))+' tỷ'}]);
$('#charts').innerHTML=panel('Doanh thu theo quý','Q1/2024–Q2/2026','ree-q')+panel('Cơ cấu doanh thu theo mảng','Quarterly breakdown · tỷ đồng','ree-mix-q')+panel('Cơ cấu doanh thu năm','2021–2025 · tỷ đồng','ree-mix-y')+panel('Doanh thu & LNST CĐ mẹ','2021–2025','ree-core');
addChart('ree-q','line',x.quarters,[{label:'Doanh thu',data:x.quarterlyRevenue,tension:.25},{label:'LNST CĐ mẹ',data:x.quarterlyNpatmi,tension:.25}],{unit:'tỷ đồng'});addChart('ree-mix-q','bar',x.quarters,Object.entries(x.quarterlySegments).map(([k,v])=>({label:k,data:v})),{stacked:true,unit:'tỷ đồng',zero:true});addChart('ree-mix-y','bar',x.years,Object.entries(x.annualSegments).map(([k,v])=>({label:k,data:v})),{stacked:true,unit:'tỷ đồng',zero:true});addChart('ree-core','line',x.years,[{label:'Doanh thu',data:x.revenue,tension:.25},{label:'LNST CĐ mẹ',data:x.npatmi,tension:.25}],{unit:'tỷ đồng'});}
function render(){destroy();const x=D[active];$('#company-title').textContent=x.title;$('#company-subtitle').textContent=x.subtitle;$('#source-state').innerHTML=`<span class="dot"></span> Nguồn: ${D.source.title} · snapshot ${D.source.capturedAt}`;$$('.company-btn').forEach(b=>b.classList.toggle('active',b.dataset.company===active));if(active==='POW')renderPOW();if(active==='FPT')renderFPT();if(active==='REE')renderREE();}
$$('.company-btn').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.company;render()}));$('#sheet-link').href=D.source.url;render();