let D=window.DATA_SNAPSHOT;let active='POW';let charts=[];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const LIVE_KEY='investment_data_hub_apps_script_url_v1';
let liveUrl=localStorage.getItem(LIVE_KEY)||'';
const fmt=(n,d=0)=>n==null?'—':Number(n).toLocaleString('vi-VN',{maximumFractionDigits:d});
const nval=v=>{if(v==null||v==='')return null;let s=String(v).trim().replace(/\s/g,'');if(!s||s==='-')return null;if(s.endsWith('%'))s=s.slice(0,-1);if(/^[-+]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))s=s.replace(/,/g,'');else if(/^[-+]?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null};
function total(series,i){return Object.values(series).reduce((s,a)=>s+(Number(a[i])||0),0)}
function pct(a,b){return b?((a/b-1)*100):null}
function yoyClass(v){return v==null?'':v>=0?'up':'down'}
function destroy(){charts.forEach(c=>c.destroy());charts=[]}
function addChart(id,type,labels,datasets,opts={}){const el=document.getElementById(id);if(!el)return;charts.push(new Chart(el,{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${fmt(c.raw,1)}${opts.unit?' '+opts.unit:''}`}}},scales:{x:{stacked:!!opts.stacked,grid:{display:false}},y:{stacked:!!opts.stacked,beginAtZero:!!opts.zero}}}}))}
function cards(items){$('#kpis').innerHTML=items.map(x=>`<div class="stat-card"><span>${x.label}</span><strong>${x.value}</strong>${x.note?`<small class="${x.cls||''}">${x.note}</small>`:''}</div>`).join('')}
function panel(title,sub,id){return `<div class="chart-card"><div class="chart-title"><div><h3>${title}</h3><span>${sub}</span></div></div><div class="chart-box"><canvas id="${id}"></canvas></div></div>`}
function monthLabel(p){const [y,m]=p.split('-');return `T${Number(m)}/${y}`}

function alignedSeries(points,periods){const names=[...new Set(points.map(x=>x.series))];const out={};for(const name of names)out[name]=periods.map(p=>points.find(x=>x.series===name&&x.period===p)?.value??null);return out}
function parsePOWRaw(rows){let year=null,metric=null;const pts={generation:[],qc:[],revenue:[]};for(const row of rows||[]){const lab=String(row?.[0]||'').trim();if(/^20\d{2}$/.test(lab)){year=lab;metric=null;continue}if(!year)continue;if(/sản lượng (phát|điện)/i.test(lab)){metric='generation';continue}if(/sản lượng qc/i.test(lab)){metric='qc';continue}if(/^doanh thu$/i.test(lab)){metric='revenue';continue}if(!metric||!lab)continue;for(let m=1;m<=12;m++){const v=nval(row[m]);if(v==null)continue;pts[metric].push({series:lab,period:`${year}-${String(m).padStart(2,'0')}`,value:v})}}
const periods=[...new Set([...pts.generation,...pts.qc,...pts.revenue].map(x=>x.period))].sort();const labels=periods.map(monthLabel);return{title:'POW — PV Power',subtitle:'Vận hành theo nhà máy · Sản lượng, Qc và doanh thu',latest:labels.at(-1)||'—',months:labels,generation:{series:alignedSeries(pts.generation,periods)},qc:{series:alignedSeries(pts.qc,periods)},revenue:{series:alignedSeries(pts.revenue,periods)}}}

function rowByLabel(rows,label,start=0){for(let i=start;i<rows.length;i++)if(String(rows[i]?.[0]||'').trim()===label)return{i,row:rows[i]};return null}
function parseFPTRaw(rows){const h=rows?.[0]||[],currentYear=new Date().getFullYear();const annual=[];for(let c=1;c<h.length;c++){const s=String(h[c]||'').trim();if(/^20\d{2}$/.test(s))annual.push({c,year:Number(s)});else if(annual.length)break}const full=annual.filter(x=>x.year<currentYear);const revR=rowByLabel(rows,'Doanh thu lũy kế (tỷ)');const pbtR=rowByLabel(rows,'LNTT lũy kế (tỷ)');if(!revR||!pbtR)throw new Error('FPT: không tìm thấy Doanh thu/LNTT lũy kế');const segNames=['Công nghệ','Nước ngoài','Chuyển đổi số','Trong nước','Viễn thông','Giáo dục và đầu tư khác'];const segRows={};for(const name of segNames){const hit=rowByLabel(rows,name,revR.i+1);if(hit&&hit.i<pbtR.i)segRows[name]=hit.row}const cur=annual.find(x=>x.year===currentYear);const years=full.map(x=>String(x.year));const vals=(row,cols)=>cols.map(x=>nval(row?.[x.c]));const ytd=(row)=>cur?nval(row?.[cur.c]):null;const monthlyRevenue=fptMonthlyTable(rows,'Doanh thu (tỷ)',['Công nghệ','Nước ngoài','Chuyển đổi số','Trong nước','Viễn thông','Giáo dục và đầu tư khác']);const monthlyPbt=fptMonthlyTable(rows,'LNTT (tỷ)',['Công nghệ','Nước ngoài','Trong nước','Viễn thông','Giáo dục và đầu tư khác']);const monthlySigning=fptMonthlyTable(rows,'Doanh thu ký mới',[]);return{title:'FPT — FPT Corporation',subtitle:`Tăng trưởng theo năm · dữ liệu ${currentYear} lũy kế`,years,revenue:vals(revR.row,full),pbt:vals(pbtR.row,full),segments:Object.fromEntries(Object.entries(segRows).map(([k,r])=>[k,vals(r,full)])),ytd2026:{year:currentYear,revenue:ytd(revR.row),technology:ytd(segRows['Công nghệ']),overseas:ytd(segRows['Nước ngoài']),pbt:ytd(pbtR.row)},monthlyRevenue,monthlyPbt,monthlySigning}}

function reeLabel(row){return String(row?.[1]||'').trim()}
function findREE(rows,test,start=0){for(let i=start;i<rows.length;i++)if(test(reeLabel(rows[i]),i))return{i,row:rows[i]};return null}
function parseQuarter(s){const m=String(s||'').trim().match(/^Q([1-4])[\/ ]?(\d{2,4})$/i);if(!m)return null;let y=m[2];if(y.length===2)y='20'+y;return{year:Number(y),q:Number(m[1]),label:`Q${m[1]}/${y}`}}
function parseREERaw(rows){const h=rows?.[1]||[],currentYear=new Date().getFullYear();const annual=[];const quarters=[];for(let c=0;c<h.length;c++){const s=String(h[c]||'').trim();if(/^20\d{2}$/.test(s)&&Number(s)>=2021&&Number(s)<currentYear)annual.push({c,year:Number(s)});const q=parseQuarter(s);if(q&&q.year>=currentYear-2)quarters.push({c,...q})}const rev=findREE(rows,l=>/^3\. Doanh thu thuần/.test(l));const np=findREE(rows,l=>/^20\. Lợi nhuận sau thuế của công ty mẹ/.test(l));const block=findREE(rows,(l,i)=>i>24&&l==='Doanh thu');if(!rev||!np||!block)throw new Error('REE: không tìm thấy block doanh thu/LNST');const segNames=['Cơ điện lạnh','Bất động sản & cho thuê văn phòng','Hạ tầng điện','Hạ tầng nước'];const segRows={};for(const name of segNames){const hit=findREE(rows,(l,i)=>i>block.i&&i<block.i+10&&l===name,block.i+1);if(hit)segRows[name]=hit.row}const vals=(row,cols)=>cols.map(x=>nval(row?.[x.c]));return{title:'REE — REE Corporation',subtitle:'Tổng hợp theo quý và cơ cấu doanh thu các mảng',years:annual.map(x=>String(x.year)),revenue:vals(rev.row,annual),npatmi:vals(np.row,annual),quarters:quarters.map(x=>x.label),quarterlyRevenue:vals(rev.row,quarters),quarterlyNpatmi:vals(np.row,quarters),annualSegments:Object.fromEntries(Object.entries(segRows).map(([k,r])=>[k,vals(r,annual)])),quarterlySegments:Object.fromEntries(Object.entries(segRows).map(([k,r])=>[k,vals(r,quarters)]))}}

function normalizeLive(raw){return{source:{title:'Investment Data Hub · Google Sheets LIVE',capturedAt:raw.capturedAt||new Date().toLocaleString('vi-VN'),url:raw.spreadsheetUrl||D.source.url,live:true},POW:parsePOWRaw(raw.sheets.POW),FPT:parseFPTRaw(raw.sheets.FPT),REE:parseREERaw(raw.sheets.REE)}}

function renderPOW(){const x=D.POW,n=x.months.length-1,prev=n-12;const gen=total(x.generation.series,n),rev=total(x.revenue.series,n),qc=total(x.qc.series,n),genYoY=prev>=0?pct(gen,total(x.generation.series,prev)):null,revYoY=prev>=0?pct(rev,total(x.revenue.series,prev)):null;cards([{label:`Sản lượng ${x.latest}`,value:fmt(gen,1)+' GWh',note:genYoY==null?'':`${genYoY>=0?'+':''}${fmt(genYoY,1)}% YoY`,cls:yoyClass(genYoY)},{label:`Qc ${x.latest}`,value:fmt(qc,1)+' GWh'},{label:`Doanh thu ${x.latest}`,value:fmt(rev,1)+' tỷ',note:revYoY==null?'':`${revYoY>=0?'+':''}${fmt(revYoY,1)}% YoY`,cls:yoyClass(revYoY)},{label:'Kỳ mới nhất',value:x.latest}]);$('#charts').innerHTML=panel('Sản lượng điện theo nhà máy','Cột chồng · GWh','pow-gen')+panel('Sản lượng Qc theo nhà máy','Cột chồng · GWh','pow-qc')+panel('Doanh thu theo nhà máy','Cột chồng · tỷ đồng','pow-rev')+panel('Tổng sản lượng và Qc','So sánh tổng hệ thống','pow-total');const ds=o=>Object.entries(o).map(([k,v])=>({label:k,data:v,borderWidth:1}));addChart('pow-gen','bar',x.months,ds(x.generation.series),{stacked:true,unit:'GWh',zero:true});addChart('pow-qc','bar',x.months,ds(x.qc.series),{stacked:true,unit:'GWh',zero:true});addChart('pow-rev','bar',x.months,ds(x.revenue.series),{stacked:true,unit:'tỷ đồng',zero:true});addChart('pow-total','line',x.months,[{label:'Sản lượng',data:x.months.map((_,i)=>total(x.generation.series,i)),tension:.25},{label:'Qc',data:x.months.map((_,i)=>total(x.qc.series,i)),tension:.25}],{unit:'GWh'})}
function fptMonthlyTableHtml(title,sub,data,preferredOrder=[]){
  if(!data||!data.months?.length)return '';
  const order=['Tổng',...preferredOrder].filter((v,i,a)=>a.indexOf(v)===i&&data.series[v]);
  const cell=(v,g)=>`<td><div class="fpt-cell-value">${v==null?'—':fmt(v)}</div><div class="fpt-cell-growth ${yoyClass(g)}">${g==null?'—':`${g>=0?'+':''}${fmt(g,1)}%`}</div></td>`;
  return `<div class="panel fpt-table-panel"><div class="chart-title"><div><h3>${title}</h3><span>${sub} · Giá trị tỷ đồng, growth YoY</span></div></div><div class="fpt-table-wrap"><table class="fpt-month-table"><thead><tr><th>Khoản mục</th>${data.months.map(m=>`<th>${m}/${String(data.year).slice(-2)}</th>`).join('')}</tr></thead><tbody>${order.map(name=>`<tr><th>${name}</th>${data.series[name].values.map((v,i)=>cell(v,data.series[name].yoy[i])).join('')}</tr>`).join('')}</tbody></table></div></div>`;
}
function renderFPT(){const x=D.FPT,n=x.years.length-1;const revYoY=pct(x.revenue[n],x.revenue[n-1]),pbtYoY=pct(x.pbt[n],x.pbt[n-1]),cy=x.ytd2026.year;cards([{label:`Doanh thu ${x.years[n]}`,value:fmt(x.revenue[n])+' tỷ',note:`${revYoY>=0?'+':''}${fmt(revYoY,1)}% YoY`,cls:yoyClass(revYoY)},{label:`LNTT ${x.years[n]}`,value:fmt(x.pbt[n])+' tỷ',note:`${pbtYoY>=0?'+':''}${fmt(pbtYoY,1)}% YoY`,cls:yoyClass(pbtYoY)},{label:`Doanh thu ${cy} YTD`,value:fmt(x.ytd2026.revenue)+' tỷ'},{label:`CNTT nước ngoài ${cy} YTD`,value:fmt(x.ytd2026.overseas)+' tỷ'}]);
  const tables=fptMonthlyTableHtml('Breakdown doanh thu theo tháng',`${cy}`,x.monthlyRevenue,['Công nghệ','Nước ngoài','Chuyển đổi số','Trong nước','Viễn thông','Giáo dục và đầu tư khác'])+
    fptMonthlyTableHtml('Breakdown LNTT theo tháng',`${cy}`,x.monthlyPbt,['Công nghệ','Nước ngoài','Trong nước','Viễn thông','Giáo dục và đầu tư khác'])+
    fptMonthlyTableHtml('Doanh thu ký mới theo tháng',`${cy}`,x.monthlySigning,[]);
  $('#charts').innerHTML=panel('Doanh thu và LNTT',`${x.years[0]}–${x.years.at(-1)} · tỷ đồng`,'fpt-core')+panel('Cơ cấu doanh thu','Các mảng chính · tỷ đồng','fpt-mix')+tables+panel('Biên LNTT','LNTT / doanh thu','fpt-margin')+panel(`Động lực ${cy} YTD`,'Tổng hợp từ Google Sheet','fpt-ytd');
  addChart('fpt-core','line',x.years,[{label:'Doanh thu',data:x.revenue,tension:.25},{label:'LNTT',data:x.pbt,tension:.25}],{unit:'tỷ đồng'});addChart('fpt-mix','bar',x.years,Object.entries(x.segments).map(([k,v])=>({label:k,data:v})),{unit:'tỷ đồng',zero:true});addChart('fpt-margin','line',x.years,[{label:'Biên LNTT',data:x.pbt.map((v,i)=>v/x.revenue[i]*100),tension:.25}],{unit:'%'});addChart('fpt-ytd','bar',['Doanh thu','Công nghệ','CNTT nước ngoài','LNTT'],[{label:`${cy} YTD`,data:[x.ytd2026.revenue,x.ytd2026.technology,x.ytd2026.overseas,x.ytd2026.pbt]}],{unit:'tỷ đồng',zero:true})}
function renderREE(){const x=D.REE,n=x.quarters.length-1,revYoY=n>=4?pct(x.quarterlyRevenue[n],x.quarterlyRevenue[n-4]):null,npYoY=n>=4?pct(x.quarterlyNpatmi[n],x.quarterlyNpatmi[n-4]):null;cards([{label:`Doanh thu ${x.quarters[n]}`,value:fmt(x.quarterlyRevenue[n])+' tỷ',note:revYoY==null?'':`${revYoY>=0?'+':''}${fmt(revYoY,1)}% YoY`,cls:yoyClass(revYoY)},{label:`LNST CĐ mẹ ${x.quarters[n]}`,value:fmt(x.quarterlyNpatmi[n])+' tỷ',note:npYoY==null?'':`${npYoY>=0?'+':''}${fmt(npYoY,1)}% YoY`,cls:yoyClass(npYoY)},{label:`Doanh thu ${x.years.at(-1)}`,value:fmt(x.revenue.at(-1))+' tỷ'},{label:`LNST CĐ mẹ ${x.years.at(-1)}`,value:fmt(x.npatmi.at(-1))+' tỷ'}]);$('#charts').innerHTML=panel('Doanh thu theo quý',`${x.quarters[0]}–${x.quarters.at(-1)}`,'ree-q')+panel('Cơ cấu doanh thu theo mảng','Quarterly breakdown · tỷ đồng','ree-mix-q')+panel('Cơ cấu doanh thu năm',`${x.years[0]}–${x.years.at(-1)} · tỷ đồng`,'ree-mix-y')+panel('Doanh thu & LNST CĐ mẹ',`${x.years[0]}–${x.years.at(-1)}`,'ree-core');addChart('ree-q','line',x.quarters,[{label:'Doanh thu',data:x.quarterlyRevenue,tension:.25},{label:'LNST CĐ mẹ',data:x.quarterlyNpatmi,tension:.25}],{unit:'tỷ đồng'});addChart('ree-mix-q','bar',x.quarters,Object.entries(x.quarterlySegments).map(([k,v])=>({label:k,data:v})),{stacked:true,unit:'tỷ đồng',zero:true});addChart('ree-mix-y','bar',x.years,Object.entries(x.annualSegments).map(([k,v])=>({label:k,data:v})),{stacked:true,unit:'tỷ đồng',zero:true});addChart('ree-core','line',x.years,[{label:'Doanh thu',data:x.revenue,tension:.25},{label:'LNST CĐ mẹ',data:x.npatmi,tension:.25}],{unit:'tỷ đồng'})}
function render(){destroy();const x=D[active];$('#company-title').textContent=x.title;$('#company-subtitle').textContent=x.subtitle;const live=D.source.live;$('#source-state').innerHTML=`<span class="dot ${live?'live':''}"></span> ${live?'LIVE':'Snapshot'} · ${D.source.capturedAt}`;$('#live-help').innerHTML=live?`<strong>Kết nối live:</strong> đang đọc trực tiếp 3 tab POW / FPT / REE từ Google Sheet. Website tự kiểm tra dữ liệu mới mỗi 60 giây.`:`<strong>Chế độ dữ liệu:</strong> đang dùng snapshot dự phòng. Bấm “Kết nối Google Sheet” sau khi bạn deploy Apps Script.`;$$('.company-btn').forEach(b=>b.classList.toggle('active',b.dataset.company===active));if(active==='POW')renderPOW();if(active==='FPT')renderFPT();if(active==='REE')renderREE();$('#sheet-link').href=D.source.url}

function setLoading(msg){$('#source-state').innerHTML=`<span class="dot loading"></span> ${msg}`}
function loadLive(){if(!liveUrl){render();return}setLoading('Đang đồng bộ Google Sheet...');const old=document.getElementById('live-data-script');if(old)old.remove();delete window.GSHEET_RAW;const s=document.createElement('script');s.id='live-data-script';s.src=liveUrl+(liveUrl.includes('?')?'&':'?')+'t='+Date.now();s.onerror=()=>{D=window.DATA_SNAPSHOT;render();$('#source-state').innerHTML='<span class="dot error"></span> Không đọc được live · đang dùng snapshot'};document.head.appendChild(s)}
window.addEventListener('gsheet-data-ready',()=>{try{D=normalizeLive(window.GSHEET_RAW);render()}catch(e){console.error(e);D=window.DATA_SNAPSHOT;render();$('#source-state').innerHTML=`<span class="dot error"></span> Lỗi parser: ${e.message}`}});
$$('.company-btn').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.company;render()}));
$('#connect-live').addEventListener('click',()=>{const v=prompt('Dán URL Web App Apps Script kết thúc bằng /exec:',liveUrl);if(v==null)return;const u=v.trim();if(!u){localStorage.removeItem(LIVE_KEY);liveUrl='';D=window.DATA_SNAPSHOT;render();return}if(!/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/.test(u)){alert('URL chưa đúng. Hãy dùng Web app URL có dạng https://script.google.com/macros/s/.../exec');return}liveUrl=u;localStorage.setItem(LIVE_KEY,u);loadLive()});
$('#refresh-live').addEventListener('click',()=>{if(!liveUrl)$('#connect-live').click();else loadLive()});
render();if(liveUrl)loadLive();setInterval(()=>{if(liveUrl)loadLive()},60000);
