const STORAGE_KEY='investment_data_hub_v4';
const SOURCE_KEY='investment_data_sources_v2';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clone=v=>JSON.parse(JSON.stringify(v));
const slugify=t=>String(t||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const fmt=n=>n==null?'—':Number(n).toLocaleString('vi-VN',{maximumFractionDigits:2});
const num=v=>{if(v==null||v==='')return null;let s=String(v).trim().replace(/\s/g,'');if(!s||s==='-')return null;if(/%$/.test(s)){const n=Number(s.replace('%','').replace(/,/g,''));return Number.isFinite(n)?n/100:null}if(/^[-+]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))s=s.replace(/,/g,'');else if(/^[-+]?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null};
const labelPeriod=p=>{if(!p)return'—';if(/^\d{4}$/.test(p))return p;if(/^\d{4}-Q[1-4]$/.test(p)){const[y,q]=p.split('-');return `${q}/${y}`}const m=p.match(/^(\d{4})-(\d{2})$/);return m?`T${Number(m[2])}/${m[1]}`:p};
const freqRank={month:3,quarter:2,year:1};

const seed={companies:[
{id:'pow',ticker:'POW',name:'PV Power',sector:'Điện',profile:'pow'},
{id:'fpt',ticker:'FPT',name:'FPT Corporation',sector:'Công nghệ thông tin',profile:'fpt'},
{id:'ree',ticker:'REE',name:'REE Corporation',sector:'Hạ tầng',profile:'ree'}
],metrics:[],observations:[]};
let state=loadState(),sources=loadSources(),activeCompanyId=state.companies[0]?.id||'pow',activeRange='all',dashboardChart=null,companyCharts=[];
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return x?.companies&&x?.metrics&&x?.observations?x:clone(seed)}catch{return clone(seed)}}
function loadSources(){try{return JSON.parse(localStorage.getItem(SOURCE_KEY)||'{}')}catch{return {}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))} function saveSources(){localStorage.setItem(SOURCE_KEY,JSON.stringify(sources))}
for(const c of seed.companies)if(!state.companies.some(x=>x.id===c.id))state.companies.push(clone(c));
function companyMetrics(id){return state.metrics.filter(m=>m.companyId===id).sort((a,b)=>(a.order||0)-(b.order||0))}
function metricRows(id){return state.observations.filter(o=>o.metricId===id)}
function bestFrequency(metricId){const fs=[...new Set(metricRows(metricId).map(x=>x.frequency||'month'))];return fs.sort((a,b)=>(freqRank[b]||0)-(freqRank[a]||0))[0]||'month'}
function metricSeries(id,freq){return[...new Set(metricRows(id).filter(x=>(x.frequency||'month')===freq).map(x=>x.series||'Tổng'))]}
function latestPeriodForCompany(id){const mids=new Set(companyMetrics(id).map(m=>m.id));return state.observations.filter(o=>mids.has(o.metricId)).map(o=>o.period).sort().at(-1)||null}
function getMetric(companyId,name,unit='',group='Google Sheets',chart='auto'){
 let m=state.metrics.find(x=>x.companyId===companyId&&x.name===name);
 if(!m){m={id:`${companyId}_${slugify(name)}_${state.metrics.length+1}`,companyId,name,unit,group,chart,order:companyMetrics(companyId).length+1};state.metrics.push(m)}
 if(unit&&!m.unit)m.unit=unit; if(group&&!m.group)m.group=group; return m;
}
function obs(companyId,metric,series,period,value,frequency,unit=''){const v=num(value);if(v==null||!period)return null;const m=getMetric(companyId,metric,unit,groupFor(metric),chartFor(metric,series));return{companyId,metricId:m.id,metricName:m.name,series:series||'Tổng',period,value:v,frequency,unit:m.unit||unit||''}}
function groupFor(n){if(/doanh thu|lntt|lnst|lợi nhuận|biên|tỷ trọng/i.test(n))return'Tài chính';if(/sản lượng|qc|giá bán điện|backlog/i.test(n))return'Vận hành';return'Khác'}
function chartFor(n,s){if(/tỷ trọng|biên|giá bán/i.test(n))return'multi-line';if(/sản lượng|qc|doanh thu theo nhà máy|theo mảng|năng lượng/i.test(n)&&s!=='Tổng')return'stacked-bar';return'line'}
function upsert(rows){let inserted=0,updated=0;for(const r of rows.filter(Boolean)){const i=state.observations.findIndex(o=>o.metricId===r.metricId&&o.series===r.series&&o.period===r.period&&(o.frequency||'month')===r.frequency);if(i>=0){state.observations[i]=r;updated++}else{state.observations.push(r);inserted++}}saveState();return{inserted,updated}}

function parsePOW(a){const out=[];let year=null,metric=null,monthStart=1;for(let r=0;r<a.length;r++){const row=a[r]||[],a0=String(row[0]||'').trim();if(/^20\d{2}$/.test(a0)){year=a0;metric=null;continue}if(!year)continue;const normalized=a0.toLowerCase();if(/sản lượng (phát|điện)/i.test(a0)){metric='Sản lượng điện';monthStart=String(row[1]||'').match(/^T?1$/i)?1:1;if(row.slice(1).some(x=>/^T\d+$/i.test(String(x||''))))continue}if(/sản lượng qc/i.test(a0)){metric='Sản lượng Qc';if(row.slice(1).some(x=>/^T\d+$/i.test(String(x||''))))continue}if(/^doanh thu$/i.test(a0)){metric='Doanh thu theo nhà máy';if(row.slice(1).some(x=>/^T\d+$/i.test(String(x||''))))continue}if(!metric||!a0||/^(sản lượng|doanh thu)/i.test(a0))continue;for(let c=1;c<=12;c++){const p=`${year}-${String(c).padStart(2,'0')}`;out.push(obs('pow',metric,a0,p,row[c], 'month',metric.includes('Doanh thu')?'tỷ đồng':'GWh'))}}return out.filter(Boolean)}

function reePeriods(header){const p=[];for(let c=0;c<header.length;c++){const s=String(header[c]||'').trim();if(/^20\d{2}$/.test(s))p[c]={period:s,frequency:'year'};else{const m=s.match(/^Q([1-4])[\/ ]?(\d{2,4})$/i);if(m){let y=m[2];if(y.length===2)y='20'+y;p[c]={period:`${y}-Q${m[1]}`,frequency:'quarter'}}} }return p}
function parseREE(a){const out=[],periods=reePeriods(a[1]||[]);let context='BCTC',anchor=null;const anchors={
'doanh thu':'Doanh thu theo mảng','lợi nhuận sau thuế':'LNST theo mảng','lợi nhuận':'Lợi nhuận năng lượng','biên lãi ròng':'Biên lãi ròng năng lượng','sản lượng điện':'Sản lượng điện','giá bán điện':'Giá bán điện'};
for(let r=2;r<a.length;r++){const row=a[r]||[],lab=String(row[1]||'').trim();if(!lab)continue;if(/^breakdown$/i.test(lab)){context='Breakdown';anchor=null;continue}if(/^mảng năng lượng$/i.test(lab)){context='Năng lượng';anchor=null;continue}if(/^input mảng m&e$/i.test(lab)){context='M&E';anchor=null;continue}if(/^mảng m&e$/i.test(lab)){context='M&E';anchor=null;continue}if(/^mảng reepro$/i.test(lab)){context='REEPRO';anchor=null;continue}if(/^mảng tech$/i.test(lab)){context='TECH';anchor=null;continue}if(/^growth yoy$/i.test(lab)||/^so với cùng kỳ$/i.test(lab)||/^\*/.test(lab))continue;
 const low=lab.toLowerCase();if(context==='Năng lượng'&&anchors[low]){anchor=anchors[low];for(let c=0;c<periods.length;c++)if(periods[c])out.push(obs('ree',anchor,'Tổng',periods[c].period,row[c],periods[c].frequency,unitREE(anchor)));continue}
 if(context==='Breakdown'&&anchors[low]){anchor=anchors[low];for(let c=0;c<periods.length;c++)if(periods[c])out.push(obs('ree',anchor,'Tổng',periods[c].period,row[c],periods[c].frequency,unitREE(anchor)));continue}
 if(['M&E','REEPRO','TECH'].includes(context)){const metric=`${context} - ${lab}`;for(let c=0;c<periods.length;c++)if(periods[c])out.push(obs('ree',metric,'Tổng',periods[c].period,row[c],periods[c].frequency,unitREE(metric)));continue}
 if(anchor&&context==='Năng lượng'){for(let c=0;c<periods.length;c++)if(periods[c])out.push(obs('ree',anchor,lab,periods[c].period,row[c],periods[c].frequency,unitREE(anchor)));continue}
 if(anchor&&context==='Breakdown'){for(let c=0;c<periods.length;c++)if(periods[c])out.push(obs('ree',anchor,lab,periods[c].period,row[c],periods[c].frequency,unitREE(anchor)));continue}
 if(/^\d+\./.test(lab)||/^- Trong đó:/.test(lab)){const metric=lab.replace(/\s*\(đồng\).*$/i,'');for(let c=0;c<periods.length;c++)if(periods[c])out.push(obs('ree',metric,'Tổng',periods[c].period,row[c],periods[c].frequency,'tỷ đồng'))}
}return out.filter(Boolean)}
function unitREE(n){if(/biên|tỷ trọng/i.test(n))return'%';if(/sản lượng/i.test(n))return'triệu kWh';if(/giá bán/i.test(n))return'đồng/kWh';return'tỷ đồng'}

function fptPeriods(h0,h1){const p=[];let year=null;for(let c=1;c<Math.max(h0.length,h1.length);c++){const top=String(h0[c]||'').trim(),sub=String(h1[c]||'').trim();if(/^20\d{2}$/.test(top))year=top;if(!year)continue;if(/^Q[1-4]$/i.test(sub))p[c]={period:`${year}-${sub.toUpperCase()}`,frequency:'quarter'};else if(/^([1-9]|1[0-2])$/.test(sub))p[c]={period:`${year}-${String(Number(sub)).padStart(2,'0')}`,frequency:'month'};else if(/^20\d{2}$/.test(top)&&!sub&&c<=10)p[c]={period:top,frequency:'year'}}return p}
function parseFPT(a){const out=[],periods=fptPeriods(a[0]||[],a[1]||[]);let anchor=null;const anchorNames=/^(Doanh thu lũy kế \(tỷ\)|Doanh thu \(tỷ\)|LNTT lũy kế \(tỷ\)|LNTT \(tỷ\)|Biên LNTT \(%\)|Tỷ trọng doanh thu|Tỷ trọng LNTT)$/i;for(let r=2;r<a.length;r++){const row=a[r]||[],lab=String(row[0]||'').trim();if(!lab)continue;if(/^Growth YoY$/i.test(lab))continue;if(anchorNames.test(lab)){anchor=lab;for(let c=1;c<periods.length;c++)if(periods[c])out.push(obs('fpt',anchor,'Tổng',periods[c].period,row[c],periods[c].frequency,unitFPT(anchor)));continue}if(!anchor)continue;if(/^(Công nghệ|Nước ngoài|Chuyển đổi số|Trong nước|Viễn thông|Giáo dục và đầu tư khác|Giáo dục|Đầu tư khác|Loại trừ hợp nhất)$/i.test(lab)){for(let c=1;c<periods.length;c++)if(periods[c])out.push(obs('fpt',anchor,lab,periods[c].period,row[c],periods[c].frequency,unitFPT(anchor)))}}
return out.filter(Boolean)}
function unitFPT(n){return /biên|tỷ trọng/i.test(n)?'%':'tỷ đồng'}
function parseByCompany(cid,rows){if(cid==='pow')return parsePOW(rows);if(cid==='ree')return parseREE(rows);if(cid==='fpt')return parseFPT(rows);return[]}

function refreshSelectors(){const opts=state.companies.map(c=>`<option value="${c.id}">${c.ticker} — ${c.name}</option>`).join('');['company-select','hub-company','input-company-select','metric-company-select'].forEach(id=>{const e=$('#'+id);if(!e)return;const old=e.value;e.innerHTML=opts;e.value=state.companies.some(c=>c.id===old)?old:activeCompanyId})}
function setView(name){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#view-'+name)?.classList.add('active-view');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const titles={dashboard:'Tổng quan dữ liệu',company:'Dữ liệu doanh nghiệp',hub:'Google Sheets Hub',manual:'Nhập tay',settings:'Cấu hình'};$('#page-title').textContent=titles[name]||'Data Hub';if(name==='dashboard')renderDashboard();if(name==='company')renderCompany();if(name==='hub')renderHub();if(name==='settings')renderSettings()}
function renderDashboard(){refreshSelectors();const latest=state.companies.map(c=>latestPeriodForCompany(c.id)).filter(Boolean).sort().at(-1);$('#summary-stats').innerHTML=[['Doanh nghiệp',state.companies.length],['Chỉ tiêu',state.metrics.length],['Điểm dữ liệu',state.observations.length],['Kỳ mới nhất',labelPeriod(latest)]].map(([a,b])=>`<div class="stat-card"><span>${a}</span><strong>${b}</strong></div>`).join('');$('#company-status-body').innerHTML=state.companies.map(c=>{const ms=companyMetrics(c.id),ids=new Set(ms.map(m=>m.id)),o=state.observations.filter(x=>ids.has(x.metricId));return`<tr><td><strong>${c.ticker}</strong></td><td>${c.name}</td><td>${c.sector}</td><td>${ms.length}</td><td>${new Set(o.map(x=>x.metricId+'|'+x.series)).size}</td><td>${labelPeriod(latestPeriodForCompany(c.id))}</td><td>${o.length}</td></tr>`}).join('');const ms=companyMetrics(activeCompanyId);$('#dashboard-metric-select').innerHTML=ms.map(m=>`<option value="${m.id}">${m.name}</option>`).join('');renderQuickChart()}
function payload(m,range='all'){const f=bestFrequency(m.id),rows=metricRows(m.id).filter(x=>(x.frequency||'month')===f),ps=[...new Set(rows.map(x=>x.period))].sort(),periods=range==='all'?ps:ps.slice(-Number(range)),series=metricSeries(m.id,f),datasets=series.map(s=>({label:s,data:periods.map(p=>rows.find(x=>x.period===p&&x.series===s)?.value??null),borderWidth:2,tension:.25,pointRadius:2}));return{f,periods,series,datasets}}
function buildChart(canvas,m,range='all'){const d=payload(m,range),type=(m.chart==='stacked-bar'||(m.chart==='auto'&&d.series.length>1))?'bar':'line',stacked=type==='bar'&&d.series.length>1;return new Chart(canvas,{type,data:{labels:d.periods.map(labelPeriod),datasets:d.datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:d.series.length>1,position:'bottom'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${fmt(c.raw)} ${m.unit||''}`}}},scales:{x:{stacked,grid:{display:false}},y:{stacked,beginAtZero:stacked}}}})}
function renderQuickChart(){const m=state.metrics.find(x=>x.id===$('#dashboard-metric-select').value)||companyMetrics(activeCompanyId)[0];if(dashboardChart)dashboardChart.destroy();if(m)dashboardChart=buildChart($('#dashboard-chart'),m)}
function renderCompany(){const c=state.companies.find(x=>x.id===activeCompanyId);if(!c)return;$('#company-title').textContent=`${c.ticker} — ${c.name}`;$('#company-subtitle').textContent=`Parser: ${c.profile.toUpperCase()} · ${companyMetrics(c.id).length} chỉ tiêu`;companyCharts.forEach(x=>x.destroy());companyCharts=[];const g=$('#charts-grid');g.innerHTML='';for(const m of companyMetrics(c.id)){const d=payload(m,activeRange),card=document.createElement('div');card.className='chart-card';card.innerHTML=`<div class="chart-title"><div><h3>${m.name}</h3><span>${m.group} · ${m.unit||'—'} · ${d.f==='month'?'tháng':d.f==='quarter'?'quý':'năm'}</span></div></div><div class="chart-box"><canvas></canvas></div>`;g.appendChild(card);companyCharts.push(buildChart(card.querySelector('canvas'),m,activeRange))}}
function renderHub(){refreshSelectors();const cid=$('#hub-company').value||activeCompanyId;$('#hub-company').value=cid;$('#sheet-csv-url').value=sources[cid]?.csvUrl||'';const profile=$('#parser-profile');if(profile){const text={pow:'POW: block năm → metric → nhà máy × tháng',ree:'REE: annual + quarterly + block theo mảng',fpt:'FPT: annual + quarterly + monthly super-wide'};profile.textContent=text[cid]||''}}
async function syncSheet(){const cid=$('#hub-company').value,url=$('#sheet-csv-url').value.trim(),s=$('#sync-status');if(!url){s.textContent='Hãy dán URL CSV publish của đúng tab doanh nghiệp.';return}s.textContent='Đang đọc Sheet theo parser '+cid.toUpperCase()+'...';try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const csv=await res.text();const parsed=Papa.parse(csv,{header:false,skipEmptyLines:false});const rows=parseByCompany(cid,parsed.data);if(!rows.length)throw new Error('Parser không nhận được dữ liệu từ layout hiện tại.');const result=upsert(rows);$('#sheet-preview-summary').textContent=`Parser ${cid.toUpperCase()} đọc ${rows.length} điểm; hiển thị 100 dòng đầu.`;$('#sheet-preview-body').innerHTML=rows.slice(0,100).map(r=>`<tr><td>${labelPeriod(r.period)}</td><td>${r.metricName}</td><td>${r.series}</td><td>${fmt(r.value)}</td><td>${r.unit||'—'}</td></tr>`).join('');sources[cid]={csvUrl:url,lastSync:new Date().toISOString()};saveSources();s.textContent=`Đồng bộ xong: ${result.inserted} mới, ${result.updated} cập nhật.`;renderDashboard()}catch(e){s.textContent='Không đồng bộ được: '+e.message}}
function saveSource(){const cid=$('#hub-company').value;sources[cid]={...(sources[cid]||{}),csvUrl:$('#sheet-csv-url').value.trim()};saveSources();$('#sync-status').textContent='Đã lưu nguồn cho '+cid.toUpperCase()}
function renderSettings(){refreshSelectors();$('#metric-list-body').innerHTML=state.metrics.map(m=>{const c=state.companies.find(x=>x.id===m.companyId),f=bestFrequency(m.id);return`<tr><td><strong>${c?.ticker||'—'}</strong></td><td>${m.name}</td><td>${m.unit||'—'}</td><td>${m.group||'—'}</td><td>${m.chart||'auto'}</td><td>${metricSeries(m.id,f).join(', ')||'—'}</td></tr>`}).join('')}
function init(){refreshSelectors();renderDashboard();$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#company-select').onchange=e=>{activeCompanyId=e.target.value;renderDashboard()};$('#dashboard-metric-select').onchange=renderQuickChart;$('#goto-hub').onclick=()=>setView('hub');$('#hub-company').onchange=renderHub;$('#save-source').onclick=saveSource;$('#sync-sheet').onclick=syncSheet;$$('.segment').forEach(b=>b.onclick=()=>{activeRange=b.dataset.range;$$('.segment').forEach(x=>x.classList.toggle('active',x===b));renderCompany()})}
document.addEventListener('DOMContentLoaded',init);